### ISSUE TITLE
Multi-lines `type`

### ISSUE THREAD

**Issue by joan38** [olafurpg/scalafmt#500]
**Version**: 0.4.4

```scala
  type Row = AlertEvent :+: InteractionEvent :+: HistoryEvent :+: PostEvent :+: ImageEvent :+: PostStatusEvent :+: VideoEvent :+: UserEvent :+: TribeEvent :+: DeviceEvent.Registered :+: TribeInviteEvent.Invited :+: CNil
```

Would it be possible to add new lines when it goes beyond the max line limite? And keep the new lines if the input is with new lines:
```scala
  type Row = AlertEvent :+:
    InteractionEvent :+:
    HistoryEvent :+:
    PostEvent :+:
    ImageEvent :+:
    PostStatusEvent :+:
    VideoEvent :+:
    UserEvent :+:
    TribeEvent :+:
    DeviceEvent.Registered :+:
    TribeInviteEvent.Invited :+:
    CNil
```

Cheers

**Comment by olafurpg** [comment]
Whoops, forgot to push that into a separate branch, accidentally pushed to master instead 😅 

Anyways, this was a bug and it should be fixed now. Those are infix type operators and should be handled identically to infix term operators, your line breaks are preserved even if that means the line limit is exceeded.

If you don't want those operators to increase the indentation by 2 spaces you need to add to your config:


```conf
unindentTopLevelOperators = true
indentOperator.exclude = ":\\+:" # is regexp, so escaping is needed
```

**Comment by joan38** [comment]
Nice @olafurpg, thanks for the fix!

**Comment by joan38** [comment]
I still have a question about why without the 2 line config it does this output:
```scala
type Row = AlertEvent :+:
  InteractionEvent :+:
    HistoryEvent :+:
      PostEvent :+:
        ImageEvent :+:
          PostStatusEvent :+:
            VideoEvent :+:
              UserEvent :+:
                TribeEvent :+:
                  DeviceEvent.Registered :+:
                    TribeInviteEvent.Invited :+:
                      CNil
```

Shouldn't it be:
```scala
type Row = AlertEvent :+:
  InteractionEvent :+:
  HistoryEvent :+:
  PostEvent :+:
  ImageEvent :+:
  PostStatusEvent :+:
  VideoEvent :+:
  UserEvent :+:
  TribeEvent :+:
  DeviceEvent.Registered :+:
  TribeInviteEvent.Invited :+:
  CNil
```
or:
```scala
type Row =
  AlertEvent :+:
  InteractionEvent :+:
  HistoryEvent :+:
  PostEvent :+:
  ImageEvent :+:
  PostStatusEvent :+:
  VideoEvent :+:
  UserEvent :+:
  TribeEvent :+:
  DeviceEvent.Registered :+:
  TribeInviteEvent.Invited :+:
  CNil
```
?

---

Also with:
```
unindentTopLevelOperators = true
indentOperator.exclude = ":\\+:|\\+" # Handle :+: and +
```
this:
```scala
type Row = AlertEvent :+:
  InteractionEvent :+:
  HistoryEvent :+:
  PostEvent :+:
  ImageEvent :+:
  PostStatusEvent :+:
  VideoEvent :+:
  UserEvent :+:
  TribeEvent :+:
  DeviceEvent.Registered :+:
  TribeInviteEvent.Invited :+:
  CNil

def t = 4 +
  3 +
  2 +
  1
```

will be formatted:
```scala
type Row = AlertEvent :+:
InteractionEvent :+:
HistoryEvent :+:
PostEvent :+:
ImageEvent :+:
PostStatusEvent :+:
VideoEvent :+:
UserEvent :+:
TribeEvent :+:
DeviceEvent.Registered :+:
TribeInviteEvent.Invited :+:
CNil

  def t =
    4 +
    3 +
    2
```

Which is perfectly fine for the `+` but it sounds strange on `:+:`?

**Comment by olafurpg** [comment]
Great question! First of all, infix operators have been incredibly tricky to get right and I agree they still more polishing to do.

This output here

```scala
type Row = AlertEvent :+:
InteractionEvent :+:
HistoryEvent :+:
DeviceEvent.Registered :+:
TribeInviteEvent.Invited :+:
CNil
```

is an unintended side-effect from trying to support formatting like this

```scala
type Row =
  AlertEvent :+:
  InteractionEvent :+:
  HistoryEvent :+:
  PostEvent :+:
  CNil
```

The first output is a bug and deserves a separate issue.

In a perfect world, we could determine the indentation from the AST. Unfortunately, that turns out be tricky for several reasons. One example:

```scala
lst.map { param =>
  // body indented at 2 spaces
}
lst.map {
  param =>
    // body indented at 4 spaces
}
```
Those two have identical asts but different indentations.

Q: Why not insert AlertEvent on a newline?
```scala
// why this
 type Row = AlertEvent :+:
    InteractionEvent :+:
    HistoryEvent :+:
    CNil
// and not this
type Row =
  AlertEvent :+:
  InteractionEvent :+:
  HistoryEvent :+:
  CNil
```
The general rule of thumb when using infix operators is that **you control the line breaks**. This includes the space/newline between `=` and `AlertEvent`.

In the earliest releases I tried to make scalafmt smarter with infix operators but it always messed up with a ton of DSLs in akka and other places.


Q: why does the indent always increase by 2?
```scala
type Row =
  AlertEvent :+:
    InteractionEvent :+:
      HistoryEvent :+:
````
A: Because the indentation for each operator expires after the last token on the right-hand side argument. In some cases this really help parse the statement. Here' how the ast for that example looks like
```scala
Defn.Type(Nil, Type.Name("Row"), Nil,
          Type.ApplyInfix(Type.Name("AlertEvent"), Type.Name(":+:"),
                          Type.ApplyInfix(Type.Name("InteractionEvent"), Type.Name(":+:"),
                                          Type.ApplyInfix(Type.Name("HistoryEvent"), Type.Name(":+:"),
                                                          Type.Name("CNil")))))
```

**Comment by joan38** [comment]
_Q: Why not insert AlertEvent on a newline?_
A: I'm perfectly fine with this. Can Scalafmt make this line break when it's a multi line type declaration?

_Q: why does the indent always increase by 2?_
So there is not workaround this?

**Comment by olafurpg** [comment]
> Can Scalafmt make this line break when it's a multi line type declaration?
> So there is no workaround this?

Of course there are always workarounds. The only question is who wants to invest the effort to make it work well against any random input ;)
